### ISSUE TITLE
Customize labels with scoped slot

### ISSUE THREAD

**Issue by SylvainMarty** [LouisMazel/vue-select-input-ui#3]
Hello Louis!
At [GUIDAP](https://guidap.co/), we have implemented a bunch of your libraries for Vue (vue-phone-number-input, vue-input-ui and this one). This is some good work! :muscle: 

## Is your feature request related to a problem? Please describe
We want to implement a country selector which must be the equivalent of the one you implemented in [vue-phone-number-input](https://louismazel.github.io/vue-phone-number-input/).
With the current implementation, we can't add HTML nor component code in the `label` property.

## Describe the solution you'd like
To do so, it would be great to expose a scoped slot we could use to display the flag of the country just before the country name.

## Describe alternatives you've considered
:grimacing:

**Comment by LouisMazel** [comment]
Hi Sylvain,

First, nice surprise ! 
And thanks for your trust. 

I think I can do something for you. 
If you can make a "template" with the `v-slot` directive, is ok for you ?
I have an example with another component here: [MazSearch](https://louismazel.github.io/maz-ui/#/documentation/search)
Click on "Show code" in the second example (Custom)

Let me know if this way is good for you and I can add this feature :)

If you like my components, you can check this library [Maz-UI](https://louismazel.github.io/maz-ui/)
It's in beta, I'm still working on it, but you can use it.

**Comment by SylvainMarty** [comment]
Hi Louis,

The `v-slot` directive is the recent way of using scoped slots so its perfect for us! :smiley: 

We checked Maz-UI but we already have an UI library for sidebar, menu and stuff like that.
We are very happy that your form components are accessible as standalone, it perfectly fits our needs. :+1:

**Comment by LouisMazel** [comment]
It's released !
[Release 1.0.6](https://github.com/LouisMazel/vue-select-input-ui/releases/tag/1.0.6)

In the demo, you can check the second example

And you can use this feature like this : 

```html
<VueSelectInputUi
  id="VueSelectInput3"
  v-model="selectedValue"
  name="VueSelectInput3"
  :options="optionsList"
  label="Custom item template"
  color="purple"
  class="mb-3"
  size="lg"
  :item-height="40"
  :border-radius="4"
  :dark="dark"
>
  <template v-slot="{ option }">
    <p>{{ option.label }} = {{ option.value }}</p>
  </template>
</VueSelectInputUi>
```

**Comment by SylvainMarty** [comment]
Wow thank you Louis, its was fast!

We will implement it in the next sprint, thank you again, you rock. :muscle:

**Comment by LouisMazel** [comment]
You're welcome

There are many evolutions in this version
If you have any issue, let me know !
